subquery/subql-ethereum

packages/node/src/ethereum/api.ethereum.ts
packages/node/src/ethereum/api.service.ethereum.test.ts
packages/node/src/ethereum/utils.ethereum.ts
packages/node/src/indexer/indexer.manager.ts

In https://github.com/subquery/subql-ethereum/pull/23 we switched using an api that provided extra parsing by Ethers, this lead to addresses not being converted to checksum addresses. This also fixes other address scenarios where this could happen.
This also fixes the order which events and transactions are handled. Rather than processing transactions followed by logs it will now process a transaction then its logs before repeating with the remaining transactions and their logs

Ensure addresses are checksum addresses

---

packages/node/src/indexer/blockDispatcher/block-dispatcher.service.ts
packages/node/src/indexer/dictionary.service.ts

Fixes error with out of order blocks when there are many dynamic datasources created

Check queue for lower blocks before processing fetched blocks

---

packages/node/src/indexer/blockDispatcher/worker-block-dispatcher.service.ts

Brings over code from main sdk that would progress the last buffered height if the dictionary result was empty.

Fix latestBufferedHeight not progressing with empty dictionary result

---

packages/node/src/ethereum/ethers/json-rpc-batch-provider.ts

If an RPC provider returns an error on a batch request, then the response is not an array but a single error response. We need to add a check to see if the response is an array or not

check result from json-rpc-batch request is array

---

packages/node/package.json
packages/node/src/indexer/fetch.service.ts
yarn.lock

`equalToInsensitive` runs very slow in cockroach, in most of cases `equalTo` is fine.
Eth-lish chain's dictionary timeout
If we are worried in some dictionary the addresses are stored in checksum format, we can replace `{address:{equalToInsensitive: $evmLogs_0_0}}` with `or: [{address:{equalTo: <lower cased address>}}, {address:{equalTo: <checksum address>}}]`, though maybe overkill.

dict use equalTo for address

---

packages/node/package.json
packages/node/src/ethereum/api.service.ethereum.ts
packages/node/src/indexer/dictionary.service.ts
packages/node/src/indexer/fetch.service.ts
yarn.lock

This is a new way of resolving chain aliases that means that we no longer need to modify dictionaries. This also works with resolving network dictionaries where previously it didn't.
It also fixes the `runtimeChain` being incorrectly used as the `chainId`. This would result in a lot of chain ids being "unknown"

New method of resolving chain alises

---

.github/workflows/pr.yml
packages/node/src/ethereum/api.service.ethereum.ts
packages/node/src/indexer/indexer.manager.ts

Currently when one endpoint that is picked to perform a contract query in the mapping failed, the node will crash. Implementing retry logic for safe api will use a different endpoint from connection pool instead of crashing.
Fixes #

Implement Retry logic for SafeEthProvider

---

packages/node/CHANGELOG.md
packages/node/src/ethereum/ethers/json-rpc-batch-provider.ts

Cache chainId in `JsonBatchRpcProvider` to prevent multiple calls to `eth_chainId`
Fixes https://github.com/subquery/subql/issues/1856

cache result from eth_chainId

---

packages/node/CHANGELOG.md
packages/node/src/ethereum/api.ethereum.test.ts
packages/node/src/ethereum/api.ethereum.ts
packages/node/src/ethereum/ethers/json-rpc-batch-provider.ts

BSC supports the `finalized` block tag but not the `safe` block tag. The check previously assumed that if `finalized` is available then `safe` was too. Now we check for each individually.

Fix finalization check on BSC

---

packages/node/CHANGELOG.md
packages/node/src/ethereum/api.ethereum.ts

With the ETH sdk we use the batch http provider by default. Some RPC endpoints don't support batch requests. We should instead fallback to using the singular provider if this happens
Fixes https://github.com/subquery/subql/issues/1941

Fallback from batch provider to singular provider

---

packages/node/CHANGELOG.md
packages/node/src/ethereum/api.ethereum.ts
packages/node/src/ethereum/ethers/celo/celo-json-rpc-batch-provider.spec.ts
packages/node/src/ethereum/ethers/celo/celo-json-rpc-batch-provider.ts
packages/node/src/ethereum/ethers/celo/celo-json-rpc-provider.spec.ts
packages/node/src/ethereum/ethers/celo/celo-json-rpc-provider.ts
packages/node/src/ethereum/ethers/celo/celo-ws-provider.spec.ts
packages/node/src/ethereum/ethers/celo/celo-ws-provider.ts
packages/node/src/ethereum/utils.ethereum.ts

Prior to the Flan hard fork, celo was not compatible with ether.js. We need a custom formatter with JsonRpcProvider to handle blocks before the Flan hard fork that happened at block 16068685

add custom provider for celo

---

packages/node/CHANGELOG.md
packages/node/src/indexer/fetch.service.spec.ts
packages/node/src/indexer/fetch.service.ts

Even only "address" provided in ds option, it still log warning like 
It should only warning when "address" and "to" in filter both exist. 

Fix address filter warning

---

packages/node/CHANGELOG.md
packages/node/src/ethereum/api.ethereum.ts

Using the block height to get logs will always return results or empty results rather than an invalid result. Switching to using the block hash guarantees we get the right logs for the block. If an endpoint is out of sync and we're unable to get the logs then retry logic will handle it.
Fixes https://github.com/subquery/subql/issues/1999

Switch to getting logs via block hash instead of block number

---

packages/common-ethereum/src/codegen/codegen-controller.ts

fix templates path

---

packages/node/CHANGELOG.md
packages/node/package.json
packages/node/src/yargs.ts
yarn.lock

fix default yargs override nodeOptions

---

packages/node/src/ethereum/block.ethereum.ts

Asserts that a log has a matching transaction. This should always be the case but rather than silently fail it would be detected.
This helps when it comes to indexing the block as we iterate on the logs within each transaction

Add assertion that logs have a matching block

---

packages/types/CHANGELOG.md
packages/types/src/project.ts

Update generics for RuntimeDatasouceTemplate

fix RuntimeDatasourceTemplate generic typing

---

packages/common-ethereum/CHANGELOG.md
packages/common-ethereum/package.json
packages/node/CHANGELOG.md
packages/node/package.json
packages/types/CHANGELOG.md
packages/types/package.json

Release for
- Fix on `subql/types-ethereum` on type-ethereum
- bump  `subql/types-ethereum` on node-ethereum
- bump  `subql/types-ethereum` on common-ethereum

[release] 20231005

---

package.json
packages/common-ethereum/package.json
packages/node/CHANGELOG.md
packages/node/package.json
packages/types/package.json
yarn.lock

[release] 20231017

---

packages/common-ethereum/CHANGELOG.md
packages/common-ethereum/package.json
packages/node/CHANGELOG.md
packages/node/package.json
packages/node/src/indexer/blockDispatcher/worker-block-dispatcher.service.ts
packages/node/src/indexer/fetch.module.ts
packages/node/src/indexer/sandbox.service.ts
packages/node/src/indexer/worker-fetch.module.ts
packages/node/src/indexer/worker/worker.inMemoryCache.service.ts
packages/types/CHANGELOG.md
packages/types/package.json
yarn.lock

[release] 20231020 eth

---

packages/node/CHANGELOG.md
packages/node/src/ethereum/api.ethereum.ts

Cronos RPC supports "safe" tag but returns block number 1. If unfinalized blocks is enabled this leads to indexing not happening because there are no blocks to index.
This adds an exlusion from using the "safe" tag on cronos

Skip using safe tag for cronos

---

.github/workflows/node-docker.yml
packages/node/Dockerfile
packages/node/Dockerfile-flare

Update CI to build docker from source

build docker from source - ethereum

---

packages/node/CHANGELOG.md
packages/node/src/ethereum/api.ethereum.test.ts
packages/node/src/ethereum/api.ethereum.ts
packages/node/src/ethereum/utils.ethereum.ts

Fixes transaction receipts not being available when accessing via logs or block.

Fix receipts missing on transactions

---

packages/node/CHANGELOG.md
packages/node/src/ethereum/api.ethereum.test.ts
packages/node/src/ethereum/api.ethereum.ts

Fixes transaction missing on log object because it was cloning the object and removing the getter function

Fix transaction getter being removed when cloning object

---

packages/node/CHANGELOG.md
packages/node/src/yargs.ts

Bring back block-confirmations arg that was accidentally removed in sync with main sdk

Bring back block confirmations arg that was removed in #210

---

packages/common-ethereum/CHANGELOG.md
packages/common-ethereum/package.json
packages/common-ethereum/src/project/models.ts
packages/common-ethereum/src/project/utils.spec.ts
packages/common-ethereum/src/project/utils.ts
yarn.lock

Update validation of filter addresses to support zilliqa addresses which use a different format to ethereum.
Fixes https://github.com/subquery/subql/issues/1996

Update ethereum address validation to include Zilliqa address

---

.yarn/versions/e10f29d6.yml
packages/node/CHANGELOG.md
packages/node/package.json

Release
- hot fix on `subql/node-ethereum`

[release] 20240118

---

packages/node/CHANGELOG.md
packages/node/package.json
packages/node/src/ethereum/api.ethereum.ts
yarn.lock

BEVM Canary doesn't support "earliest" block tag so this PR adds a special case for that network

Add special case to genesis hash for BEVM canary

---

packages/common-ethereum/CHANGELOG.md
packages/common-ethereum/src/project/models.ts
packages/node/CHANGELOG.md
packages/node/src/ethereum/api.ethereum.test.ts
packages/node/src/ethereum/api.ethereum.ts
packages/node/src/ethereum/block.ethereum.ts
packages/node/src/indexer/fetch.service.ts
packages/types/CHANGELOG.md
packages/types/src/ethereum/interfaces.ts

Update transaction filters to support native transfers with no input data.
```ts
{
kind: EthereumHandlerKind.Call,
handler: "handleTransaction",
filter: {
function: "0x",
},
},
```
```ts
{
kind: EthereumHandlerKind.Call,
handler: "handleTransaction",
filter: {
function: null,
},
},
```

Add the ability to filter for native transfers

---

packages/common-ethereum/CHANGELOG.md
packages/common-ethereum/src/codegen/codegen-controller.spec.ts
packages/common-ethereum/src/codegen/codegen-controller.ts
packages/common-ethereum/test/abiTest/abis/contract_with_overloads.json

Codegen was not generating matching names with typechain when function arguments are more complex. This will now generate the correct type arguments by resolving `tuple` and `tuple[]`
Fixes https://github.com/subquery/subql/issues/2231

Fix codegen with complex argument types

---

packages/node/CHANGELOG.md
packages/node/src/indexer/dictionary.service.spec.ts
packages/node/src/indexer/dictionary.service.ts

Add error handling for fetching chain aliases and switch to built in fetch from node-fetch, this should hopefully fix issues with HTTP_PROXY and HTTPS_PROXY node flags

Add error handling for getting chain aliases

---

packages/node/CHANGELOG.md
packages/node/src/ethereum/api.ethereum.test.ts
packages/node/src/ethereum/api.ethereum.ts

Certain rpc do not support getLogs param blockHash, so in order to accomodate for that we must throw if the log's blockHash does not align with the blockHash

Add assertion on fetchBlock for mismatched blockHash

---

packages/node/CHANGELOG.md
packages/node/src/indexer/dictionary/v1/ethDictionaryV1.spec.ts
packages/node/src/indexer/dictionary/v1/ethDictionaryV1.ts
packages/node/src/indexer/dictionary/v2/ethDictionaryV2.spec.ts
packages/node/src/indexer/dictionary/v2/ethDictionaryV2.ts
packages/node/src/indexer/dictionary/v2/types.ts

- Fixes dictionary v1 query being empty for any block handler, now considers modulo filters
- Fixes dictionary v2 returning with a partial query if there were no filters and considers modulo filters

Fix dictionary queries when there are block filters with modulos

---

packages/node/CHANGELOG.md
packages/node/src/ethereum/api.ethereum.test.ts
packages/node/src/ethereum/api.ethereum.ts
packages/node/src/ethereum/api.service.ethereum.test.ts
packages/node/src/ethereum/api.service.ethereum.ts
packages/node/src/indexer/dictionary/v1/ethDictionaryV1.spec.ts
packages/node/src/indexer/dictionary/v2/ethDictionaryV2.spec.ts
packages/node/src/indexer/dictionary/v2/utils.spec.ts
packages/node/src/indexer/project.service.test.ts

In order to support api keys in headers we convert query params to headers, this stripped the query params, there was no need to strip the query params, this keeps the query params as provided in the config

Fix query params being stripped

---

packages/node/CHANGELOG.md
packages/node/src/configure/SubqueryProject.ts
packages/node/src/utils/project.ts

Fixes an issue caused from removing Flare alias which could result in either a `Cannot find module` or `Failed to load datasource asset` error.

Fix data sources not loading

---

packages/common-ethereum/package.json
packages/types/package.json
packages/types/src/index.ts
yarn.lock

fix missing export modular

---

packages/common-ethereum/src/index.ts
packages/types/src/modular.ts

Strict export type to be `EthereumNetworkModule`, and dedicated method should not be optional.

strict types

---

packages/node/CHANGELOG.md
packages/node/package.json
packages/node/src/configure/SubqueryProject.ts
packages/node/src/configure/configure.module.ts
yarn.lock

Use Subquery Project from node core

---

packages/common-ethereum/CHANGELOG.md
packages/common-ethereum/package.json
packages/common-ethereum/src/project/versioned/v1_0_0/model.ts
packages/node/CHANGELOG.md
packages/node/package.json
packages/node/src/ethereum/api.connection.ts
packages/node/src/ethereum/api.ethereum.ts
packages/node/src/ethereum/api.service.ethereum.ts
packages/node/src/indexer/dictionary/v2/ethDictionaryV2.spec.ts
packages/types/CHANGELOG.md
packages/types/package.json
packages/types/src/project.ts
yarn.lock

Update dependencies and support for network endpoint configs including setting headers and batch sizes.

Add support for endpoint config headers and batch size

---

packages/node/CHANGELOG.md
packages/node/src/indexer/dictionary/v2/ethDictionaryV2.spec.ts
packages/node/src/indexer/dictionary/v2/ethDictionaryV2.ts

If the dictionary v2 response contained no blocks then it would result in indexing each block within that range manually. This fixes that by making sure the last buffered height is set to the end block of the requested range.

Fix dict last buffered

---

packages/common-ethereum/CHANGELOG.md
packages/common-ethereum/src/codegen/codegen-controller.spec.ts
packages/common-ethereum/src/codegen/codegen-controller.ts
packages/common-ethereum/src/project/utils.ts
packages/node/CHANGELOG.md
packages/node/src/ethereum/api.ethereum.test.ts
packages/node/src/ethereum/block.ethereum.ts
packages/node/src/indexer/dictionary/v1/ethDictionaryV1.ts
packages/node/src/indexer/dictionary/v2/ethDictionaryV2.spec.ts
packages/node/src/indexer/dictionary/v2/ethDictionaryV2.ts

With a recent validation improvement to check filters exist in ABIs, there was no check to allow the `!null` filter. This adds it in.
Also defines a const to a void magic strings for '!null'

Fix filter validation with not null filter

---

package.json
packages/node/CHANGELOG.md
packages/node/src/indexer/dictionary/utils.spec.ts
packages/node/src/indexer/dictionary/utils.ts
packages/node/src/indexer/dictionary/v1/ethDictionaryV1.spec.ts
packages/node/src/indexer/dictionary/v1/ethDictionaryV1.ts
packages/node/src/indexer/dictionary/v2/ethDictionaryV2.spec.ts
packages/node/src/indexer/dictionary/v2/ethDictionaryV2.ts
yarn.lock

A couple of improvements to dictionary queries:
* Don't base grouping off templates name, this was a regression where the name was no longer available and so grouping wouldn't occur. So now it groups on matching filters.
* Fixes not using dict, when a handler has no filters but an address was set in the options. This is an edge case.

Fixes and optimisations to dictionary queries

---

.yarn/versions/28107c27.yml
.yarn/versions/6c9eef4c.yml
packages/common-ethereum/CHANGELOG.md
packages/common-ethereum/package.json
packages/node/CHANGELOG.md
packages/node/package.json
yarn.lock

Bump common, Added manifest support for query-subgraph.

[release] 20240925

---

packages/node/CHANGELOG.md
packages/node/src/ethereum/api.ethereum.test.ts
packages/node/src/ethereum/block.ethereum.ts

Do not index data when fullBlock does not exist logs.
Fixes https://github.com/subquery/subql/issues/2575

Do not index data when fullBlock does not exist logs

---

packages/node/CHANGELOG.md
packages/node/package.json

[release] 20241024

---

packages/node/CHANGELOG.md
packages/node/src/subcommands/reindex.module.ts

Fixed the reindex runtime issue caused by missing API dependencies during reindexing

Fix reindex module

---

packages/node/CHANGELOG.md
packages/node/src/ethereum/utils.ethereum.ts
packages/node/src/indexer/unfinalizedBlocks.service.spec.ts

When using historical: timestamp, because getHeader does not return the timestamp, it causes the crawl to not function properly.

Fix `Header` not found `timestamp` field

---

.github/workflows/gh-release.yml
.github/workflows/node-docker.yml
.github/workflows/pr.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/scripts/benchmark/Dockerfile
.github/workflows/sync-deps.yml
deploy/k8s/README.md
package.json
packages/node/CHANGELOG.md
packages/node/Dockerfile
packages/node/src/ethereum/ethers/json-rpc-batch-provider.ts
packages/node/src/ethereum/ethers/web/index.ts
yarn.lock

Updates to using node lts for docker images and pipelines.

Update to using node lts

---

.yarn/versions/2d421220.yml
.yarn/versions/c9a0b187.yml
.yarn/versions/d5795e98.yml
.yarn/versions/e823cdf5.yml
packages/common-ethereum/CHANGELOG.md
packages/common-ethereum/package.json
packages/node/CHANGELOG.md
packages/node/package.json
packages/types/CHANGELOG.md
packages/types/package.json
yarn.lock

[release] 20250225
