subquery/subql-ethereum

packages/node/package.json, packages/node/src/ethereum/api.ethereum.ts, packages/node/src/indexer/fetch.service.ts, packages/node/src/utils/project.ts, yarn.lock
Fixes # https://github.com/subquery/subql/issues/1293
=> Add req retry when request fails

packages/common-ethereum/src/project/project.spec.ts, packages/common-ethereum/src/project/versioned/v1_0_0/model.ts
=> fix publish missing templates name

packages/node/src/ethereum/api.ethereum.ts
Uses a single RPC request to get transaction receipts rather than one for each transaction. It will fall back to one per transaction of the RPC method is unavailable.
=> Use much more efficent rpc method for getting block receipts

packages/node/src/indexer/dynamic-ds.service.ts
Options were not being applied to runtime ds, this change adds the options as well as validates the dynamic ds
=> Fix args not being applied to runtime dynamic ds

packages/common-ethereum/src/project/models.ts, packages/common-ethereum/src/project/types.ts, packages/common-ethereum/src/project/versioned/v0_3_0/model.ts, packages/common-ethereum/src/project/versioned/v1_0_0/model.ts, packages/node/src/indexer/fetch.service.ts, packages/types/src/ethereum/interfaces.ts, packages/types/src/project.ts
solves https://github.com/subquery/subql/issues/1478 and https://github.com/subquery/subql/issues/1479
=> Filter validation

packages/common-ethereum/src/project/models.ts, packages/common-ethereum/src/project/project.spec.ts, packages/common-ethereum/test/project_1.0.0.yaml
=> fix deployment template missing options

packages/node/src/ethereum/api.ethereum.ts, packages/node/src/ethereum/safe-api.ts, packages/types/src/interfaces.ts
Fixes api requests not using the current height being indexed
=> Add safe api that only queries at the current height

packages/node/src/indexer/blockDispatcher/worker-block-dispatcher.service.ts, packages/node/src/indexer/dynamic-ds.service.ts, packages/node/src/indexer/project.service.ts, packages/node/src/indexer/worker/worker.ts
Fixes issues with dynamic datasources and worker threads. Due to there being multiple instances of dynamic ds service the state needs to be managed correctly in each instance.
=> Fix error with tempDsRecords being undefined

packages/node/src/indexer/fetch.service.ts
=> fix build dictionary query got dsOptions undefined

packages/node/src/ethereum/api.ethereum.ts, packages/node/src/ethereum/block.ethereum.ts, packages/node/src/ethereum/utils.ethereum.ts, packages/node/src/indexer/blockDispatcher/worker-block-dispatcher.service.ts, packages/node/src/indexer/indexer.manager.ts, packages/node/src/indexer/project.service.ts, packages/node/src/utils/project.ts, packages/types/src/ethereum/interfaces.ts
* Uses hex values for block numbers instead of decimal values to be compatible with polygon
* Tries using `finalized` and `safe` block tags for finalization and falls back to latest (latest - 15) 
=> Fix not working with polygon and other chains without POS

packages/node/src/indexer/fetch.service.ts
Improve dictionary query by using `equalTo`
=> Improve eth dictionary query building

packages/node/src/indexer/fetch.service.ts
=> fix the interval issue

packages/node/src/ethereum/api.ethereum.ts, packages/node/src/ethereum/api.service.ethereum.ts, packages/node/src/ethereum/ethers/json-rpc-batch-provider.ts, packages/node/src/ethereum/ethers/json-rpc-provider.ts, packages/node/src/ethereum/ethers/web/_version.ts, packages/node/src/ethereum/ethers/web/geturl.ts, packages/node/src/ethereum/ethers/web/index.ts, packages/node/src/ethereum/ethers/web/types.ts, packages/node/src/indexer/blockDispatcher/block-dispatcher.service.ts, packages/node/src/indexer/blockDispatcher/worker-block-dispatcher.service.ts, packages/node/src/indexer/indexer.manager.ts, packages/node/src/meta/meta.service.ts, packages/node/src/utils/string.ts
- Use customised providers with support for http agents and keep alive
- Use batch processor
- Use built in provider retry logic
=> Block fetching improvements

packages/node/src/indexer/dynamic-ds.service.ts
=> fix project template could undefined

packages/node/src/ethereum/api.ethereum.ts
=> improve api init logging

packages/node/package.json, packages/node/src/yargs.ts, yarn.lock
=> sync with main sdk store cache 0.0.4

packages/node/package.json, packages/node/src/ethereum/api.ethereum.ts, packages/node/src/ethereum/ethers/json-rpc-batch-provider.ts, packages/node/src/indexer/worker/worker.service.ts, yarn.lock
=> Add dns cache lookup to http agents

packages/node/src/indexer/project.service.ts, packages/node/src/subcommands/reindex.module.ts
=> Fix reindex, remove unsynced code

.yarn/versions/06519ea8.yml, .yarn/versions/4fbecedf.yml, .yarn/versions/60830d59.yml, .yarn/versions/6e85943d.yml, .yarn/versions/83b76bea.yml, .yarn/versions/8b7fc6fb.yml, .yarn/versions/8cb4e126.yml, .yarn/versions/b0e01308.yml, .yarn/versions/da0fb4a8.yml, .yarn/versions/e7785a3e.yml, .yarn/versions/fddb83b2.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json
=> [release] major release

packages/node/package.json, packages/node/src/ethereum/api.ethereum.ts, packages/node/src/ethereum/api.service.ethereum.test.ts, packages/node/src/indexer/blockDispatcher/worker-block-dispatcher.service.ts, packages/node/src/indexer/indexer.module.ts, packages/node/src/indexer/project.service.ts, packages/node/src/indexer/worker/worker.ts, packages/types/src/interfaces.ts, yarn.lock
=> Fix dynamic ds issues, tests

packages/node/package.json, yarn.lock
=> update to use node-core 0.0.5

packages/node/CHANGELOG.md, packages/node/package.json
=> bump to 1.0.2-2

.yarn/versions/f75a3d9a.yml, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20230412

packages/node/package.json, packages/node/src/ethereum/api.service.ethereum.ts, packages/node/src/ethereum/ethers/json-rpc-batch-provider.ts, packages/node/src/indexer/blockDispatcher/block-dispatcher.service.ts, packages/node/src/indexer/fetch.module.ts, packages/node/src/indexer/indexer.module.ts, packages/node/src/indexer/worker/worker.service.ts, yarn.lock
Create a `fetchBlocks` function in `EthereumApiService` to rotate between available APIs upon failure.
=> Create `fetchBlocks` in `EthereumApiService`

packages/node/src/ethereum/api.ethereum.ts, packages/node/src/yargs.ts
Fixes https://github.com/subquery/subql/issues/1524
=> Add flag to specify number of block confiramtions

packages/node/package.json, yarn.lock
=> update to 1.11.3-storeCache-0.0.1

packages/common-ethereum/package.json, yarn.lock
=> Remove unused dependency

packages/node/package.json, yarn.lock
=> try fix node-fetch import issue

packages/node/package.json, yarn.lock
=> update to node-core 2.0.1-4

packages/node/src/indexer/fetch.service.ts
=> fix fetch dictionary meta log

packages/node/package.json, packages/node/src/yargs.ts, yarn.lock
=> update node-core to fix metadata not found issue

packages/node/CHANGELOG.md, packages/node/package.json
=> Release 20230512

packages/node/CHANGELOG.md
=> [release] 20230512 v2

packages/node/CHANGELOG.md, packages/node/package.json
=> [release] node 2.1.2

packages/node/package.json, yarn.lock
Fixes https://github.com/subquery/subql/pull/1698
=> bump node-core for storeCache fix

packages/node/src/ethereum/api.service.ethereum.ts, packages/node/src/indexer/fetch.module.ts, packages/node/src/indexer/fetch.service.ts, packages/node/src/indexer/unfinalizedBlocks.service.ts
Some small tidy up.
- Stops api service being init twice
- Avoids unnecessary extra request getting finalized head.
=> Clean up some code

packages/common-ethereum/package.json, packages/node/package.json, packages/node/src/indexer/blockDispatcher/worker-block-dispatcher.service.ts, packages/node/src/indexer/worker/worker.unfinalizedBlocks.service.ts, yarn.lock
* pin vm2 to 3.9.17
* upgrade @subql/node-core to 2.1.4-5
=> upgrade to latest node-core

packages/node/CHANGELOG.md, packages/node/package.json
=> fix prerelease failed 20230519

.github/workflows/flare-prerelease.yml, .github/workflows/gh-release.yml, .github/workflows/pr.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, packages/node/Dockerfile, packages/node/Dockerfile-flare
=> [SKIP CI] update to node 18

packages/node/src/ethereum/api.ethereum.ts
Improve the check to determine the finalization mechanism for different chains. It adds a timeout because of some weird behaviour from ethers with a partially synced node that would cause the promise to never resolve
=> Update finalization check to work with arbitrum

packages/node/package.json, yarn.lock
=> fix multiple graphql due to multiple version @subql/util

.github/PULL_REQUEST_TEMPLATE.md, .github/actions/create-release/gh-release-script.js, .github/workflows/scripts/gh-release-script.js, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json, yarn.lock
Fixes publishing releases to main repo
=> [release] 20230522 eth

packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json
=> [release] 20230522 fix

packages/node/src/ethereum/api.ethereum.ts, packages/node/src/ethereum/utils.ethereum.ts, packages/types/src/ethereum/interfaces.ts
Fixes # ()
Adding block.timestamp to `eth_transaction`
=> add timestamp to eth_transaction

packages/node/src/ethereum/api.ethereum.test.ts, packages/node/src/ethereum/api.ethereum.ts, packages/node/test/erc721.json
Decode `logs` on `transactions`
=> parse tx logs and decode

packages/node/CHANGELOG.md, packages/node/package.json, yarn.lock
=> [release] 20230602

.yarn/versions/447d2440.yml, .yarn/versions/56b4831a.yml, .yarn/versions/875fb56a.yml, .yarn/versions/f7153fc9.yml, packages/node/CHANGELOG.md, packages/node/package.json, packages/node/src/subcommands/mmrRegenerate.init.ts, yarn.lock
=> [release] 20230607

.yarn/versions/79124148.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, yarn.lock
=> [release] 20230613

jest.config.js, package.json, packages/node/CHANGELOG.md, packages/node/src/indexer/fetch.service.spec.ts, packages/node/src/indexer/fetch.service.ts, yarn.lock
=> Support to field being null with dictionary query, jest fixes

.yarn/versions/4dbc5691.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json
New release for multiple endpoint improvements and dictionary query fixes
=> [release] 20230615

packages/node/CHANGELOG.md, packages/node/src/ethereum/api.ethereum.test.ts, packages/node/src/ethereum/block.ethereum.ts
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> add tests and support for filterTransactionsProcessor

packages/node/src/indexer/fetch.service.ts
=> add missing logger to fetchService

packages/node/src/ethereum/api.service.ethereum.test.ts, packages/node/src/ethereum/api.service.ethereum.ts, packages/node/src/ethereum/utils.ethereum.ts, packages/types/CHANGELOG.md
Expose the error code for api.ethereum requests to allow error handling with SDK projects
Follow up on #110 
=> add error code to thrown api request

packages/node/CHANGELOG.md, packages/node/src/indexer/dynamic-ds.service.ts, packages/node/src/indexer/fetch.service.spec.ts, packages/node/src/indexer/fetch.service.ts
Fix dictionary queries when using dynamic DS
=> fix for dynamicDs dictionary queries

packages/node/src/indexer/fetch.service.ts
=> log out length instead of address

packages/node/src/ethereum/safe-api.ts
Fixes https://github.com/subquery/subql/issues/1857
=> support getNetwork in safeApi

packages/node/CHANGELOG.md, packages/node/package.json, packages/node/src/yargs.ts, yarn.lock
=> Update node-core, add store-cache-upper-limit flag

.yarn/versions/c1ef82b4.yml, .yarn/versions/cbec37f2.yml, packages/node/CHANGELOG.md, packages/node/package.json, yarn.lock
=> [release] 20230705

packages/node/CHANGELOG.md, packages/node/package.json, yarn.lock
=> [release] 20230707

packages/node/src/ethereum/api.ethereum.test.ts, packages/node/src/ethereum/utils.ethereum.ts, packages/types/src/ethereum/interfaces.ts
Fixes https://github.com/subquery/subql/issues/1880
=> Missing format transaction in log

packages/node/CHANGELOG.md, packages/node/package.json, packages/node/src/ethereum/api.connection.ts, packages/node/src/indexer/fetch.module.ts, packages/node/src/indexer/project.service.ts, yarn.lock
=> sync with node-core 20230711

.yarn/versions/78b2b939.yml, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20230712

packages/node/CHANGELOG.md, packages/node/src/ethereum/api.service.ethereum.test.ts, packages/node/src/ethereum/api.service.ethereum.ts
A better way to implement
https://github.com/subquery/subql-ethereum/pull/133
=> Retry logic on selected errors

packages/node/CHANGELOG.md, packages/node/src/ethereum/api.ethereum.test.ts, packages/node/src/ethereum/block.ethereum.ts, packages/node/src/indexer/fetch.service.spec.ts, packages/node/src/indexer/fetch.service.ts
=> Add support for `!null` log filter 

.github/workflows/benchmark.yml, .github/workflows/scripts/benchmark/Dockerfile, .github/workflows/scripts/benchmark/benchmarking.sh, .github/workflows/scripts/benchmark/cleanHistory.sh, .github/workflows/scripts/benchmark/queryMeta.sh
Benchmarking this project https://github.com/subquery/subquery-example-ens
=> [SKIP CI] add benchmark for eth

.yarn/versions/9013fae3.yml, .yarn/versions/bffeedf7.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json
=> [release] 20230731

.yarn/versions/92710011.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json
=> [release] 20230814

packages/node/CHANGELOG.md, packages/node/src/indexer/fetch.service.spec.ts, packages/node/src/indexer/fetch.service.ts
Fixes https://github.com/subquery/subql/issues/1961
=> Fix missing ds option in event query entries

packages/node/src/indexer/fetch.service.spec.ts, packages/node/src/indexer/fetch.service.ts
=> Fix option address field

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, yarn.lock
=> [release] 20230901

packages/node/CHANGELOG.md, packages/node/package.json, yarn.lock
=> [release] 20230901 patch2

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json
=> [release] 20230904

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, yarn.lock
=> Fix unknown reader, lock to subqk/common 2.6.0

.yarn/versions/a7a64424.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20230904 patch2

packages/node/CHANGELOG.md, packages/node/src/main.ts
=> fix reindex

.github/workflows/benchmark.yml, .github/workflows/scripts/benchmark/benchmarking.sh
- use endpoint from provider, like:  `wss://eth.api.onfinality.io/ws?apikey=`
- set key as secret in the repo, with name `NETWORK_API_KEY`
- and set `true` for **Use api endpoint key** when run benchmark
=> [SKIP CI] benchmark update

packages/node/CHANGELOG.md, packages/node/package.json, yarn.lock
=> fix version issue for nestjs-prometheus

packages/node/CHANGELOG.md, packages/node/package.json, yarn.lock
=> [release] 20230912 patch2

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/src/codegen/codegen-controller.spec.ts, packages/common-ethereum/templates/abi-interface.ts.ejs, packages/node/CHANGELOG.md, packages/node/src/configure/NodeConfig.ts, packages/node/src/ethereum/api.connection.ts, packages/node/src/ethereum/api.ethereum.test.ts, packages/node/src/ethereum/api.ethereum.ts, packages/node/src/ethereum/api.service.ethereum.ts, packages/node/src/ethereum/block.ethereum.ts, packages/node/src/indexer/blockDispatcher/block-dispatcher.service.ts, packages/node/src/indexer/blockDispatcher/worker-block-dispatcher.service.ts, packages/node/src/indexer/indexer.manager.ts, packages/node/src/indexer/project.service.test.ts, packages/node/src/indexer/project.service.ts, packages/node/src/indexer/types.ts, packages/node/src/indexer/unfinalizedBlocks.service.ts, packages/node/src/indexer/worker/worker.service.ts, packages/node/src/indexer/worker/worker.unfinalizedBlocks.service.ts, packages/node/src/subcommands/testing.service.ts, packages/node/src/utils/project.ts, packages/node/src/yargs.ts, packages/types/CHANGELOG.md, packages/types/src/ethereum/interfaces.ts, packages/types/src/interfaces.ts, packages/types/src/project.ts
Add support for `skipTransaction` feature which allows skipping fetching transactions, this reduces network bandwidth as well as memory usage. https://github.com/subquery/documentation/pull/400
- Rename flag from `skipBlock` to `skipTransaction`
- Add yargs option
=> Implement skipTransaction feature

.github/workflows/benchmark.yml
=> [SKIP CI] update benchmark endpoint key name

.yarn/versions/73068a82.yml, .yarn/versions/8953dda9.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json
=> [release] 3.0.0 eth

packages/node/CHANGELOG.md, packages/node/package.json, packages/node/src/main.ts
=> [release] 3.0.1

packages/node/package.json, yarn.lock
=> Sync 20231012 node core

.yarn/versions/3971241a.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/node/src/yargs.ts
=> [release] 20231012

.github/workflows/node-docker.yml
Update Node-to-Docker CI to publish docker images under subquerynetwork org
=> publish docker image under subquerynetwork

.yarn/versions/6fda5556.yml, .yarn/versions/9ec6b350.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json
=> [release] 20231101

.github/workflows/node-docker.yml, packages/node/Dockerfile, packages/node/Dockerfile-flare, scripts/build.sh, tsconfig.json
=> [SKIP CI]Fix docker publish ci

.github/workflows/node-docker.yml
=> add context to docker push actions

packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20231108

.github/workflows/node-docker.yml, packages/node/Dockerfile, packages/node/Dockerfile-flare
=> install node globally in docker

.github/workflows/node-docker.yml, .github/workflows/scripts/update_flare_imports.sh, packages/node/Dockerfile, packages/node/Dockerfile-flare
=> fix node-gyp issue in arm64 docker

.github/workflows/node-docker.yml
=> [SKIP CI] fix release trigger pipeline

packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20231113

packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20231123 eth

packages/node/CHANGELOG.md, packages/node/package.json, yarn.lock
=> [release] 20231128 eth

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/src/codegen/codegen-controller.spec.ts, packages/common-ethereum/src/codegen/codegen-controller.ts
DS assets can be an object or a Map, this fix supports both types of assets
=> Support assets being a map or object

packages/node/CHANGELOG.md, packages/node/src/configure/SubqueryProject.ts, packages/node/src/ethereum/block.ethereum.ts
Fixes timestamp filters not being implemented and running on every block
=> Add missing filtering for timestamp

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20240108

packages/node/src/ethereum/block.ethereum.ts
=> hot fix on .timestamp

.yarn/versions/668319a7.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/types/CHANGELOG.md, packages/types/package.json
Release for:
- common-ethereum
- types
=> [release] 20240202

packages/node/CHANGELOG.md, packages/node/src/ethereum/api.ethereum.test.ts, packages/node/src/ethereum/api.ethereum.ts
=> Improve log hash assertion message

packages/node/package.json, packages/node/src/indexer/dictionary/ethDictionary.service.ts, packages/node/src/indexer/dictionary/v2/ethDictionaryV2.spec.ts, yarn.lock
Needs fixes from https://github.com/subquery/subql/pull/2322
=> Use ethereum for dict v2 tests, add more tests

packages/node/src/indexer/dictionary/v2/ethDictionaryV2.spec.ts, packages/node/src/indexer/dictionary/v2/utils.spec.ts
=> Update test endpoint

packages/node/CHANGELOG.md, packages/node/src/indexer/fetch.module.ts
=> allow workers set to 0

packages/node/CHANGELOG.md, packages/node/src/indexer/indexer.manager.ts, packages/node/src/indexer/worker/worker.service.ts
=> Fix missing apiService

packages/node/CHANGELOG.md, packages/node/package.json, packages/node/src/indexer/fetch.service.ts, yarn.lock
=> [release] 20240405 Eth

packages/node/CHANGELOG.md, packages/node/src/indexer/dictionary/ethDictionary.service.ts, packages/node/src/indexer/dictionary/v1/ethDictionaryV1.ts, packages/node/src/indexer/dictionary/v2/ethDictionaryV2.spec.ts, packages/node/src/indexer/dictionary/v2/ethDictionaryV2.ts
* Fixes v2 dictionary queries not including to field for transactions when provided in datasource options.
* Improve logging and logger names
=> Fix v2 queries missing addresses for transactions, improve logging

.github/workflows/node-docker.yml, .github/workflows/release.yml, scripts/update_versions.sh
- Escape commit message
- Set output using latest github actions method
- Update release script
=> Minor CI fixes

.github/workflows/release.yml, packages/node/CHANGELOG.md, packages/node/package.json, packages/node/src/indexer/dictionary/v2/utils.spec.ts, packages/node/src/indexer/indexer.manager.ts, packages/types/CHANGELOG.md, packages/types/package.json, packages/types/src/global.ts, yarn.lock
Fixes a bug there the unsafeApi is the wrong value and doesn't match the type. Also updates the type to better represent the injected unsafeApi
=> Fix unsafe api injecting wrong type

.yarn/versions/8128c19a.yml, .yarn/versions/b186778e.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20240605 eth

packages/node/CHANGELOG.md
=> [release] 20240605

packages/node/CHANGELOG.md, packages/node/package.json, packages/node/src/admin/admin.module.ts, yarn.lock
=> [release] 20240606

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/src/codegen/codegen-controller.spec.ts, packages/common-ethereum/src/codegen/codegen-controller.ts
Improve ABI validation
[subql/issues/2296](https://github.com/subquery/subql/issues/2296)
=> 20240606 abi validation

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json
=> [release] 20240607 abi

packages/common-ethereum/CHANGELOG.md
=> [release] 20240607-abi

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json
=> [release] 20240607-abi 3.8.1

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/src/codegen/codegen-controller.spec.ts, packages/common-ethereum/src/codegen/codegen-controller.ts
Data source options and abi is optional, this fixes abi validation when its not defined
=> Fix abi validation when DS has no abi specified

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/src/codegen/codegen-controller.ts
=> Fix generateAbis when datasource without assets

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json
=> [release] 20240611

.yarn/versions/43acd24b.yml, .yarn/versions/6382cca5.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json
=> [release] 20240612 deprecated flare

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/src/index.ts, packages/common-ethereum/src/project/index.ts, packages/types/CHANGELOG.md, packages/types/package.json, packages/types/src/modular.ts, yarn.lock
=> support export eth network module

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/src/project/utils.ts, packages/node/CHANGELOG.md, packages/types/CHANGELOG.md, packages/types/src/modular.ts
=> move getAbiInterface to common-eth

.yarn/versions/35d0cdaf.yml, .yarn/versions/52a7ab18.yml, .yarn/versions/e8b2457e.yml, .yarn/versions/f7889baf.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json
=> [release] 20240704 patch2

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/src/codegen/codegen-controller.spec.ts, packages/common-ethereum/src/codegen/codegen-controller.ts, packages/common-ethereum/src/project/models.ts, packages/common-ethereum/src/project/utils.ts, packages/common-ethereum/src/project/versioned/ProjectManifestVersioned.ts, packages/common-ethereum/src/project/versioned/v1_0_0/model.ts, packages/common-ethereum/tsconfig.json, packages/types/CHANGELOG.md, packages/types/src/project.ts
Enable TS strict model in common-ethereum package
=> Strict common ethereum

.yarn/versions/33a7b2bc.yml, .yarn/versions/f0188dc6.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json, yarn.lock
=> [release] 20240710

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/node/src/ethereum/api.service.ethereum.test.ts, packages/node/src/indexer/fetch.service.ts, packages/types/CHANGELOG.md, packages/types/package.json, yarn.lock
Improve indexer could stall due to rpc finalized height could be smaller than previous result
See how this could happen in https://gist.github.com/jiqiang90/ea640b07d298bca7cbeed4aee50776de
=> improve fetch handle rpc finalized height rollback

.yarn/versions/13aa486e.yml, .yarn/versions/41f53ef0.yml, .yarn/versions/bccad4bf.yml, .yarn/versions/c195972b.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json
=> [release] 20240711

packages/node/CHANGELOG.md, packages/node/Dockerfile, packages/node/package.json
Fix node dockerfile missing set timezone to UTC
=> [release] 20240716

.yarn/versions/147cea42.yml, .yarn/versions/150b82fe.yml, .yarn/versions/453b5731.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json
=> [release] 20240726

.github/workflows/scripts/benchmark/Dockerfile
=> [SKIPCI] set benchmark timezone

.github/workflows/scripts/benchmark/Dockerfile
=> [SKIPCI] fix benchmark write permission

.yarn/versions/8b3f9def.yml, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json
=> [release] 20241022

.yarn/versions/062e6b0f.yml, .yarn/versions/3780c2f6.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json, yarn.lock
=> [release] Bump `@subql/common` dependency

.yarn/versions/549fdc68.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20241128

.yarn/versions/1f0d9d06.yml, .yarn/versions/37f5f411.yml, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20241217

packages/node/CHANGELOG.md, packages/node/package.json, yarn.lock
=> [release] 20250320

packages/node/CHANGELOG.md, packages/node/src/ethereum/ethers/web/index.ts
With large amounts of data being received from the RPC, there was a step to decode data from a byte array to JSON. This used an inefficient JS function which has now been replaced with the TextEncoder
=> Fix decoding buffer into JSON OOM issue

README.md, babel.config.js, jest.config.js, package.json, packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/src/project/models.ts, packages/node/CHANGELOG.md, packages/node/package.json, packages/node/src/ethereum/api.ethereum.test.ts, packages/node/src/ethereum/api.service.ethereum.test.ts, packages/node/src/ethereum/block.ethereum.ts, packages/node/src/ethereum/ethers/json-rpc-batch-provider.ts, packages/node/src/ethereum/utils.ethereum.ts, packages/node/src/indexer/dictionary/v2/ethDictionaryV2.spec.ts, packages/node/src/indexer/dictionary/v2/ethDictionaryV2.ts, packages/node/src/indexer/dictionary/v2/types.ts, packages/types/CHANGELOG.md, packages/types/src/ethereum/interfaces.ts, test/jest-setup.ts, yarn.lock
Support for blobs.
* Update types to include new fields on block and transaction
* Add new `type` filter for transactions
* Update dictionary v2 to support `type` filter and detect capabilities of the dictionary service
* Sync readme with main repo
* Update node core
=> Add support for ERC 4844

packages/common-ethereum/CHANGELOG.md, packages/common-ethereum/package.json, packages/node/CHANGELOG.md, packages/node/Dockerfile, scripts/build.sh
Fix codegen failing because of missing templates in package
Apply changes to building docker image to reduce size
=> Fix templates being excluded from @subql/common-ethereum package
